/**
 * Site-wide SEO defaults (§17).
 *
 * Per-page values from PageData.seo and Markdown frontmatter are layered on top
 * of these defaults by the usePageHead hook. Kept serializable (no React) so the
 * sitemap/validation scripts could reuse it if needed.
 */
import { wikiEnv } from "./env";
import { igemStatic } from "./igemStatic";
import { buildCanonicalUrl } from "./envShared";

// Same token order as every page title's "· <team> <year> iGEM" suffix, so
// og:site_name and <title> read identically in social embeds.
export const siteName = `${wikiEnv.teamName} ${wikiEnv.teamYear} iGEM`;

/**
 * Default social share image. Override per page via PageSEO.ogImage.
 *
 * Absolute URL on purpose: og:image must be a full URL for crawlers
 * (Facebook/WeChat do not resolve origin-relative paths). Hosted on
 * static.igem.wiki (PNG uploads are converted to AVIF). The source PNG is
 * still generated by `bun scripts/generate-og.ts` from scripts/og/og-card.html.
 */
export const defaultOgImage = igemStatic.ogImage;

/** Intrinsic size of the default share image (og:image:width/height). */
export const defaultOgImageWidth = 1200;
export const defaultOgImageHeight = 630;

/** og:image:alt / twitter:image:alt for the default share image. */
export const defaultOgImageAlt =
  "Hand-drawn HEAL banner taped onto a lab-notebook page, with the motto " +
  `"Healthier, happier companions" — ${wikiEnv.teamName} iGEM ${wikiEnv.teamYear}.`;

export const defaultKeywords: string[] = [
  "iGEM",
  wikiEnv.teamName,
  "synthetic biology",
  wikiEnv.teamYear,
];

export const twitterCard = "summary_large_image";

/** Organization JSON-LD injected on every page as a baseline entity. */
export const organizationJsonLd: Record<string, unknown> = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: siteName,
  url: buildCanonicalUrl(wikiEnv.siteUrl, "/"),
  logo: igemStatic.logo,
};
